export type Word = {
  id: number;
  hu: string;
  ja: string;
  pos: string; // Part of Speech
  audio?: string;
  level: 'A1' | 'A2' | 'B1';
  category?: string;
};

const data: Word[] = [
  // --- 挨拶 (Greetings) ---
  { id: 1, hu: 'szia', ja: 'やあ / さようなら', pos: '間投詞', level: 'A1', category: '挨拶' },
  { id: 2, hu: 'köszönöm', ja: 'ありがとう', pos: '間投詞', level: 'A1', category: '挨拶' },
  { id: 3, hu: 'jó reggelt', ja: 'おはよう', pos: '挨拶', level: 'A1', category: '挨拶' },
  { id: 4, hu: 'jó napot', ja: 'こんにちは', pos: '挨拶', level: 'A1', category: '挨拶' },
  { id: 5, hu: 'jó estét', ja: 'こんばんは', pos: '挨拶', level: 'A1', category: '挨拶' },
  { id: 6, hu: 'viszontlátásra', ja: 'さようなら（改まった表現）', pos: '挨拶', level: 'A1', category: '挨拶' },

  // --- 疑問詞 (Interrogatives) ---
  { id: 10, hu: 'mi?', ja: '何？', pos: '疑問詞', level: 'A1', category: '文法' },
  { id: 11, hu: 'ki?', ja: '誰？', pos: '疑問詞', level: 'A1', category: '文法' },
  { id: 12, hu: 'hol?', ja: 'どこ？', pos: '疑問詞', level: 'A1', category: '文法' },
  { id: 13, hu: 'mikor?', ja: 'いつ？', pos: '疑問詞', level: 'A1', category: '文法' },
  { id: 14, hu: 'miért?', ja: 'なぜ？', pos: '疑問詞', level: 'A1', category: '文法' },
  { id: 15, hu: 'hogy?', ja: 'どうやって？', pos: '疑問詞', level: 'A1', category: '文法' },

  // --- 基本動詞 (Basic Verbs) ---
  { id: 20, hu: 'van', ja: 'ある / いる', pos: '動詞', level: 'A1', category: '動詞' },
  { id: 21, hu: 'szeret', ja: '愛する / 好む', pos: '動詞', level: 'A1', category: '動詞' },
  { id: 22, hu: 'eszik', ja: '食べる', pos: '動詞', level: 'A1', category: '動詞' },
  { id: 23, hu: 'iszik', ja: '飲む', pos: '動詞', level: 'A1', category: '動詞' },
  { id: 24, hu: 'megy', ja: '行く', pos: '動詞', level: 'A1', category: '動詞' },
  { id: 25, hu: 'jön', ja: '来る', pos: '動詞', level: 'A1', category: '動詞' },
  { id: 26, hu: 'tanul', ja: '学ぶ / 勉強する', pos: '動詞', level: 'A1', category: '動詞' },
  { id: 27, hu: 'dolgozik', ja: '働く', pos: '動詞', level: 'A1', category: '動詞' },
  { id: 28, hu: 'alszik', ja: '眠る', pos: '動詞', level: 'A1', category: '動詞' },
  { id: 29, hu: 'beszél', ja: '話す', pos: '動詞', level: 'A1', category: '動詞' },
  { id: 30, hu: 'ért', ja: '理解する', pos: '動詞', level: 'A1', category: '動詞' },
  { id: 31, hu: 'tud', ja: '知っている / できる', pos: '動詞', level: 'A1', category: '動詞' },
  { id: 32, hu: 'vásárol', ja: '買う / 買い物する', pos: '動詞', level: 'A1', category: '動詞' },
  { id: 33, hu: 'lát', ja: '見る / 見える', pos: '動詞', level: 'A1', category: '動詞' },
  { id: 34, hu: 'hall', ja: '聞く / 聞こえる', pos: '動詞', level: 'A1', category: '動詞' },
  { id: 35, hu: 'ír', ja: '書く', pos: '動詞', level: 'A1', category: '動詞' },
  { id: 36, hu: 'olvas', ja: '読む', pos: '動詞', level: 'A1', category: '動詞' },
  { id: 37, hu: 'kér', ja: '頼む / お願いする', pos: '動詞', level: 'A1', category: '動詞' },
  { id: 38, hu: 'főz', ja: '料理する', pos: '動詞', level: 'A1', category: '動詞' },
  { id: 39, hu: 'játszik', ja: '遊ぶ / 演奏する', pos: '動詞', level: 'A1', category: '動詞' },

  // --- 食事・飲み物 (Food & Drink) ---
  { id: 40, hu: 'víz', ja: '水', pos: '名詞', level: 'A1', category: '食事' },
  { id: 41, hu: 'alma', ja: 'りんご', pos: '名詞', level: 'A1', category: '食事' },
  { id: 42, hu: 'kenyér', ja: 'パン', pos: '名詞', level: 'A1', category: '食事' },
  { id: 43, hu: 'sör', ja: 'ビール', pos: '名詞', level: 'A1', category: '食事' },
  { id: 44, hu: 'bor', ja: 'ワイン', pos: '名詞', level: 'A1', category: '食事' },
  { id: 45, hu: 'kávé', ja: 'コーヒー', pos: '名詞', level: 'A1', category: '食事' },
  { id: 46, hu: 'tea', ja: 'お茶', pos: '名詞', level: 'A1', category: '食事' },
  { id: 47, hu: 'tej', ja: '牛乳', pos: '名詞', level: 'A1', category: '食事' },
  { id: 48, hu: 'sajt', ja: 'チーズ', pos: '名詞', level: 'A1', category: '食事' },
  { id: 49, hu: 'hús', ja: '肉', pos: '名詞', level: 'A1', category: '食事' },
  { id: 50, hu: 'hal', ja: '魚', pos: '名詞', level: 'A1', category: '食事' },
  { id: 51, hu: 'zöldség', ja: '野菜', pos: '名詞', level: 'A1', category: '食事' },
  { id: 52, hu: 'gyümölcs', ja: '果物', pos: '名詞', level: 'A1', category: '食事' },
  { id: 53, hu: 'vacsora', ja: '夕食', pos: '名詞', level: 'A1', category: '食事' },
  { id: 54, hu: 'ebéd', ja: '昼食', pos: '名詞', level: 'A1', category: '食事' },
  { id: 55, hu: 'reggeli', ja: '朝食', pos: '名詞', level: 'A1', category: '食事' },
  { id: 56, hu: 'tojás', ja: '卵', pos: '名詞', level: 'A1', category: '食事' },
  { id: 57, hu: 'cukor', ja: '砂糖', pos: '名詞', level: 'A1', category: '食事' },
  { id: 58, hu: 'só', ja: '塩', pos: '名詞', level: 'A1', category: '食事' },
  { id: 59, hu: 'paprika', ja: 'パプリカ', pos: '名詞', level: 'A1', category: '食事' },

  // --- 数字 (Numbers) ---
  { id: 60, hu: 'egy', ja: '1', pos: '数詞', level: 'A1', category: '数字' },
  { id: 61, hu: 'kettő', ja: '2', pos: '数詞', level: 'A1', category: '数字' },
  { id: 62, hu: 'három', ja: '3', pos: '数詞', level: 'A1', category: '数字' },
  { id: 63, hu: 'négy', ja: '4', pos: '数詞', level: 'A1', category: '数字' },
  { id: 64, hu: 'öt', ja: '5', pos: '数詞', level: 'A1', category: '数字' },
  { id: 65, hu: 'hat', ja: '6', pos: '数詞', level: 'A1', category: '数字' },
  { id: 66, hu: 'hét', ja: '7', pos: '数詞', level: 'A1', category: '数字' },
  { id: 67, hu: 'nyolc', ja: '8', pos: '数詞', level: 'A1', category: '数字' },
  { id: 68, hu: 'kilenc', ja: '9', pos: '数詞', level: 'A1', category: '数字' },
  { id: 69, hu: 'tíz', ja: '10', pos: '数詞', level: 'A1', category: '数字' },
  { id: 70, hu: 'húsz', ja: '20', pos: '数詞', level: 'A1', category: '数字' },
  { id: 71, hu: 'száz', ja: '100', pos: '数詞', level: 'A1', category: '数字' },
  { id: 72, hu: 'ezer', ja: '1000', pos: '数詞', level: 'A1', category: '数字' },

  // --- 家族 (Family) ---
  { id: 80, hu: 'család', ja: '家族', pos: '名詞', level: 'A1', category: '家族' },
  { id: 81, hu: 'apa', ja: '父', pos: '名詞', level: 'A1', category: '家族' },
  { id: 82, hu: 'anya', ja: '母', pos: '名詞', level: 'A1', category: '家族' },
  { id: 83, hu: 'szülők', ja: '両親', pos: '名詞', level: 'A1', category: '家族' },
  { id: 84, hu: 'testvér', ja: '兄弟姉妹', pos: '名詞', level: 'A1', category: '家族' },
  { id: 85, hu: 'fiú', ja: '少年 / 息子', pos: '名詞', level: 'A1', category: '家族' },
  { id: 86, hu: 'lány', ja: '少女 / 娘', pos: '名詞', level: 'A1', category: '家族' },
  { id: 87, hu: 'gyerek', ja: '子供', pos: '名詞', level: 'A1', category: '家族' },
  { id: 88, hu: 'férj', ja: '夫', pos: '名詞', level: 'A1', category: '家族' },
  { id: 89, hu: 'feleség', ja: '妻', pos: '名詞', level: 'A1', category: '家族' },
  { id: 90, hu: 'nagymama', ja: '祖母', pos: '名詞', level: 'A1', category: '家族' },
  { id: 91, hu: 'nagypapa', ja: '祖父', pos: '名詞', level: 'A1', category: '家族' },

  // --- 色 (Colors) ---
  { id: 100, hu: 'szín', ja: '色', pos: '名詞', level: 'A1', category: '色' },
  { id: 101, hu: 'szürke', ja: '灰色', pos: '形容詞', level: 'A1', category: '色' },
  { id: 102, hu: 'piros', ja: '赤', pos: '形容詞', level: 'A1', category: '色' },
  { id: 103, hu: 'kék', ja: '青', pos: '形容詞', level: 'A1', category: '色' },
  { id: 104, hu: 'zöld', ja: '緑', pos: '形容詞', level: 'A1', category: '色' },
  { id: 105, hu: 'sárga', ja: '黄色', pos: '形容詞', level: 'A1', category: '色' },
  { id: 106, hu: 'fehér', ja: '白', pos: '形容詞', level: 'A1', category: '色' },
  { id: 107, hu: 'fekete', ja: '黒', pos: '形容詞', level: 'A1', category: '色' },
  { id: 108, hu: 'barna', ja: '茶色', pos: '形容詞', level: 'A1', category: '色' },
  { id: 109, hu: 'lila', ja: '紫', pos: '形容詞', level: 'A1', category: '色' },
  { id: 110, hu: 'narancssárga', ja: 'オレンジ色', pos: '形容詞', level: 'A1', category: '色' },

  // --- 時間 (Time) ---
  { id: 120, hu: 'hétfő', ja: '月曜日', pos: '名詞', level: 'A1', category: '時間' },
  { id: 121, hu: 'kedd', ja: '火曜日', pos: '名詞', level: 'A1', category: '時間' },
  { id: 122, hu: 'szerda', ja: '水曜日', pos: '名詞', level: 'A1', category: '時間' },
  { id: 123, hu: 'csütörtök', ja: '木曜日', pos: '名詞', level: 'A1', category: '時間' },
  { id: 124, hu: 'péntek', ja: '金曜日', pos: '名詞', level: 'A1', category: '時間' },
  { id: 125, hu: 'szombat', ja: '土曜日', pos: '名詞', level: 'A1', category: '時間' },
  { id: 126, hu: 'vasárnap', ja: '日曜日', pos: '名詞', level: 'A1', category: '時間' },
  { id: 127, hu: 'ma', ja: '今日', pos: '副詞', level: 'A1', category: '時間' },
  { id: 128, hu: 'holnap', ja: '明日', pos: '副詞', level: 'A1', category: '時間' },
  { id: 129, hu: 'tegnap', ja: '昨日', pos: '副詞', level: 'A1', category: '時間' },
  { id: 130, hu: 'most', ja: '今', pos: '副詞', level: 'A1', category: '時間' },
  { id: 131, hu: 'óra', ja: '時間 / 時計', pos: '名詞', level: 'A1', category: '時間' },
  { id: 132, hu: 'perc', ja: '分', pos: '名詞', level: 'A1', category: '時間' },
  { id: 133, hu: 'reggel', ja: '朝', pos: '名詞', level: 'A1', category: '時間' },
  { id: 134, hu: 'este', ja: '晩', pos: '名詞', level: 'A1', category: '時間' },
  { id: 135, hu: 'nap', ja: '日', pos: '名詞', level: 'A1', category: '時間' },
  { id: 136, hu: 'hét', ja: '週', pos: '名詞', level: 'A1', category: '時間' },
  { id: 137, hu: 'hónap', ja: '月（暦）', pos: '名詞', level: 'A1', category: '時間' },
  { id: 138, hu: 'év', ja: '年', pos: '名詞', level: 'A1', category: '時間' },
  { id: 139, hu: 'évszak', ja: '季節', pos: '名詞', level: 'A1', category: '時間' },

  // --- 場所 (Places) ---
  { id: 140, hu: 'hely', ja: '場所', pos: '名詞', level: 'A1', category: '場所' },
  { id: 141, hu: 'város', ja: '都市 / 町', pos: '名詞', level: 'A1', category: '場所' },
  { id: 142, hu: 'utca', ja: '通り', pos: '名詞', level: 'A1', category: '場所' },
  { id: 143, hu: 'iskola', ja: '学校', pos: '名詞', level: 'A1', category: '場所' },
  { id: 144, hu: 'bolt', ja: '店', pos: '名詞', level: 'A1', category: '場所' },
  { id: 145, hu: 'piac', ja: '市場', pos: '名詞', level: 'A1', category: '場所' },
  { id: 146, hu: 'állomás', ja: '駅', pos: '名詞', level: 'A1', category: '場所' },
  { id: 147, hu: 'repülőtér', ja: '空港', pos: '名詞', level: 'A1', category: '場所' },
  { id: 148, hu: 'szoba', ja: '部屋', pos: '名詞', level: 'A1', category: '場所' },
  { id: 149, hu: 'étterem', ja: 'レストラン', pos: '名詞', level: 'A1', category: '場所' },
  { id: 150, hu: 'iroda', ja: '事務所 / 会社', pos: '名詞', level: 'A1', category: '場所' },
  { id: 151, hu: 'kórház', ja: '病院', pos: '名詞', level: 'A1', category: '場所' },
  { id: 152, hu: 'park', ja: '公園', pos: '名詞', level: 'A1', category: '場所' },
  { id: 153, hu: 'színház', ja: '劇場', pos: '名詞', level: 'A1', category: '文化' },
  { id: 154, hu: 'múzeum', ja: '博物館 / 美術館', pos: '名詞', level: 'A1', category: '文化' },

  // --- 形容詞 (Adjectives) ---
  { id: 160, hu: 'jó', ja: '良い', pos: '形容詞', level: 'A1', category: '形容詞' },
  { id: 161, hu: 'rossz', ja: '悪い', pos: '形容詞', level: 'A1', category: '形容詞' },
  { id: 162, hu: 'nagy', ja: '大きい', pos: '形容詞', level: 'A1', category: '形容詞' },
  { id: 163, hu: 'kicsi', ja: '小さい', pos: '形容詞', level: 'A1', category: '形容詞' },
  { id: 164, hu: 'szép', ja: '美しい / きれいな', pos: '形容詞', level: 'A1', category: '形容詞' },
  { id: 165, hu: 'csúnya', ja: '醜い', pos: '形容詞', level: 'A1', category: '形容詞' },
  { id: 166, hu: 'meleg', ja: '暖かい', pos: '形容詞', level: 'A1', category: '形容詞' },
  { id: 167, hu: 'hideg', ja: '冷たい / 寒い', pos: '形容詞', level: 'A1', category: '形容詞' },
  { id: 168, hu: 'olcsó', ja: '安い', pos: '形容詞', level: 'A1', category: '形容詞' },
  { id: 169, hu: 'drága', ja: '高い（値段が）', pos: '形容詞', level: 'A1', category: '形容詞' },
  { id: 170, hu: 'gyors', ja: '速い', pos: '形容詞', level: 'A1', category: '形容詞' },
  { id: 171, hu: 'lassú', ja: '遅い', pos: '形容詞', level: 'A1', category: '形容詞' },
  { id: 172, hu: 'könnyű', ja: '簡単 / 軽い', pos: '形容詞', level: 'A1', category: '形容詞' },
  { id: 173, hu: 'nehéz', ja: '難しい / 重い', pos: '形容詞', level: 'A1', category: '形容詞' },
  { id: 174, hu: 'finom', ja: 'おいしい', pos: '形容詞', level: 'A1', category: '形容詞' },
  { id: 175, hu: 'boldog', ja: '幸せな', pos: '形容詞', level: 'A1', category: '形容詞' },
  { id: 176, hu: 'szomorú', ja: '悲しい', pos: '形容詞', level: 'A1', category: '形容詞' },
  { id: 177, hu: 'fáradt', ja: '疲れた', pos: '形容詞', level: 'A1', category: '形容詞' },
  { id: 178, hu: 'érdekes', ja: '興味深い / 面白い', pos: '形容詞', level: 'A1', category: '形容詞' },
  { id: 179, hu: 'unalmas', ja: '退屈な', pos: '形容詞', level: 'A1', category: '形容詞' },

  // --- 体・衣服 (Body & Clothing) ---
  { id: 180, hu: 'fej', ja: '頭', pos: '名詞', level: 'A1', category: '体' },
  { id: 181, hu: 'szem', ja: '目', pos: '名詞', level: 'A1', category: '体' },
  { id: 182, hu: 'fül', ja: '耳', pos: '名詞', level: 'A1', category: '体' },
  { id: 183, hu: 'orr', ja: '鼻', pos: '名詞', level: 'A1', category: '体' },
  { id: 184, hu: 'száj', ja: '口', pos: '名詞', level: 'A1', category: '体' },
  { id: 185, hu: 'kéz', ja: '手', pos: '名詞', level: 'A1', category: '体' },
  { id: 186, hu: 'láb', ja: '足', pos: '名詞', level: 'A1', category: '体' },
  { id: 187, hu: 'test', ja: '体', pos: '名詞', level: 'A1', category: '体' },
  { id: 188, hu: 'ruha', ja: '服', pos: '名詞', level: 'A1', category: '日常' },
  { id: 189, hu: 'cipő', ja: '靴', pos: '名詞', level: 'A1', category: '日常' },

  // --- 動物 (Animals) ---
  { id: 190, hu: 'kutya', ja: '犬', pos: '名詞', level: 'A1', category: '動物' },
  { id: 191, hu: 'macska', ja: '猫', pos: '名詞', level: 'A1', category: '動物' },
  { id: 192, hu: 'madár', ja: '鳥', pos: '名詞', level: 'A1', category: '動物' },
  { id: 193, hu: 'ló', ja: '馬', pos: '名詞', level: 'A1', category: '動物' },
  { id: 194, hu: 'tehén', ja: '牛', pos: '名詞', level: 'A1', category: '動物' },
  { id: 195, hu: 'nyúl', ja: 'うさぎ', pos: '名詞', level: 'A1', category: '動物' },

  // --- 趣味・自然 (Hobbies & Nature) ---
  { id: 200, hu: 'zene', ja: '音楽', pos: '名詞', level: 'A1', category: '趣味' },
  { id: 201, hu: 'film', ja: '映画', pos: '名詞', level: 'A1', category: '趣味' },
  { id: 202, hu: 'sport', ja: 'スポーツ', pos: '名詞', level: 'A1', category: '趣味' },
  { id: 203, hu: 'utazás', ja: '旅行', pos: '名詞', level: 'A1', category: '趣味' },
  { id: 204, hu: 'idő', ja: '時間 / 天気', pos: '名詞', level: 'A1', category: '日常' },
  { id: 205, hu: 'napfény', ja: '日光', pos: '名詞', level: 'A1', category: '自然' },
  { id: 206, hu: 'eső', ja: '雨', pos: '名詞', level: 'A1', category: '自然' },
  { id: 207, hu: 'szél', ja: '風', pos: '名詞', level: 'A1', category: '自然' },
  { id: 208, hu: 'hó', ja: '雪', pos: '名詞', level: 'A1', category: '自然' },
  { id: 209, hu: 'virág', ja: '花', pos: '名詞', level: 'A1', category: '自然' },

  // --- 家・家具 (House & Furniture) ---
  { id: 210, hu: 'ház', ja: '家', pos: '名詞', level: 'A1', category: '家' },
  { id: 211, hu: 'lakás', ja: 'アパート / 住居', pos: '名詞', level: 'A1', category: '家' },
  { id: 212, hu: 'ajtó', ja: 'ドア', pos: '名詞', level: 'A1', category: '家' },
  { id: 213, hu: 'ablak', ja: '窓', pos: '名詞', level: 'A1', category: '家' },
  { id: 214, hu: 'asztal', ja: 'テーブル', pos: '名詞', level: 'A1', category: '家' },
  { id: 215, hu: 'szék', ja: '椅子', pos: '名詞', level: 'A1', category: '家' },
  { id: 216, hu: 'ágy', ja: 'ベッド', pos: '名詞', level: 'A1', category: '家' },
  { id: 217, hu: 'konyha', ja: '台所', pos: '名詞', level: 'A1', category: '家' },

  // --- 交通・旅行 (Transport & Travel) ---
  { id: 220, hu: 'autó', ja: '車', pos: '名詞', level: 'A1', category: '交通' },
  { id: 221, hu: 'busz', ja: 'バス', pos: '名詞', level: 'A1', category: '交通' },
  { id: 222, hu: 'vonat', ja: '電車', pos: '名詞', level: 'A1', category: '交通' },
  { id: 223, hu: 'bicikli', ja: '自転車', pos: '名詞', level: 'A1', category: '交通' },
  { id: 224, hu: 'hajó', ja: '船', pos: '名詞', level: 'A1', category: '交通' },
  { id: 225, hu: 'repülő', ja: '飛行機', pos: '名詞', level: 'A1', category: '交通' },
  { id: 226, hu: 'jegy', ja: 'チケット / 切符', pos: '名詞', level: 'A1', category: '交通' },
  { id: 227, hu: 'útlevél', ja: 'パスポート', pos: '名詞', level: 'A1', category: '旅行' },

  // --- 感情・状態 (Emotions & States) ---
  { id: 230, hu: 'örül', ja: '喜ぶ', pos: '動詞', level: 'A2', category: '感情' },
  { id: 231, hu: 'fél', ja: '怖がる', pos: '動詞', level: 'A2', category: '感情' },
  { id: 232, hu: 'remél', ja: '希望する', pos: '動詞', level: 'A2', category: '感情' },
  { id: 233, hu: 'segít', ja: '助ける', pos: '動詞', level: 'A2', category: '日常' },
  { id: 234, hu: 'hív', ja: '呼ぶ', pos: '動詞', level: 'A2', category: '日常' },
  { id: 235, hu: 'keres', ja: '探す', pos: '動詞', level: 'A2', category: '日常' },
  { id: 236, hu: 'talál', ja: '見つける', pos: '動詞', level: 'A2', category: '日常' },
  { id: 237, hu: 'vállal', ja: '引き受ける', pos: '動詞', level: 'A2', category: '日常' },
  { id: 238, hu: 'felejt', ja: '忘れる', pos: '動詞', level: 'A2', category: '日常' },
  { id: 239, hu: 'emlékszik', ja: '覚えている', pos: '動詞', level: 'A2', category: '日常' },

  // --- 抽象概念・テクノロジー (Abstract & Tech) ---
  { id: 250, hu: 'szerelem', ja: '愛', pos: '名詞', level: 'A2', category: '感情' },
  { id: 251, hu: 'barátság', ja: '友情', pos: '名詞', level: 'A2', category: '感情' },
  { id: 252, hu: 'élet', ja: '生活 / 人生', pos: '名詞', level: 'A1', category: '日常' },
  { id: 253, hu: 'világ', ja: '世界', pos: '名詞', level: 'A1', category: '日常' },
  { id: 254, hu: 'számítógép', ja: 'コンピュータ', pos: '名詞', level: 'A2', category: '技術' },
  { id: 255, hu: 'internet', ja: 'インターネット', pos: '名詞', level: 'A1', category: '技術' },
  { id: 256, hu: 'telefon', ja: '電話', pos: '名詞', level: 'A1', category: '日常' },
  { id: 257, hu: 'üzenet', ja: 'メッセージ', pos: '名詞', level: 'A2', category: '日常' },
  { id: 258, hu: 'kérdés', ja: '質問', pos: '名詞', level: 'A1', category: '文法' },
  { id: 259, hu: 'válasz', ja: '答え', pos: '名詞', level: 'A1', category: '文法' },

  // --- ハンガリー文化・名物 (Hungarian Culture) ---
  { id: 270, hu: 'gulyás', ja: 'グヤーシュ（スープ）', pos: '名詞', level: 'A1', category: '文化' },
  { id: 271, hu: 'balaton', ja: 'バラトン湖', pos: '名詞', level: 'A1', category: '文化' },
  { id: 272, hu: 'puszta', ja: 'プスタ（大草原）', pos: '名詞', level: 'A2', category: '文化' },
  { id: 273, hu: 'borozó', ja: 'ワインバー', pos: '名詞', level: 'A1', category: '文化' },
  { id: 274, hu: 'fürdő', ja: '温泉 / 風呂', pos: '名詞', level: 'A1', category: '文化' },
  { id: 275, hu: 'paprika', ja: 'パプリカ（香辛料）', pos: '名詞', level: 'A1', category: '文化' },
  { id: 276, hu: 'túró rudi', ja: 'トゥーロー・ルディ（お菓子）', pos: '名詞', level: 'A1', category: '文化' },
  { id: 277, hu: 'lángos', ja: 'ラーンゴシュ（揚げパン）', pos: '名詞', level: 'A1', category: '文化' },

  // --- 動作・日常動作 (Daily Actions) ---
  { id: 280, hu: 'felébred', ja: '目が覚める', pos: '動詞', level: 'A2', category: '日常' },
  { id: 281, hu: 'felkel', ja: '起きる', pos: '動詞', level: 'A1', category: '日常' },
  { id: 282, hu: 'fogat mos', ja: '歯を磨く', pos: '動詞句', level: 'A1', category: '日常' },
  { id: 283, hu: 'zuhanyozik', ja: 'シャワーを浴びる', pos: '動詞', level: 'A1', category: '日常' },
  { id: 284, hu: 'felöltözik', ja: '着替える', pos: '動詞', level: 'A2', category: '日常' },
  { id: 285, hu: 'reggelizik', ja: '朝食を食べる', pos: '動詞', level: 'A1', category: '日常' },
  { id: 286, hu: 'elindul', ja: '出発する', pos: '動詞', level: 'A2', category: '日常' },
  { id: 287, hu: 'hazamegy', ja: '家へ帰る', pos: '動詞', level: 'A1', category: '日常' },
  { id: 288, hu: 'pihen', ja: '休む', pos: '動詞', level: 'A1', category: '日常' },
  { id: 289, hu: 'takarít', ja: '掃除する', pos: '動詞', level: 'A2', category: '日常' },

  // --- 学校・教育 (School & Education) ---
  { id: 300, hu: 'egyetem', ja: '大学', pos: '名詞', level: 'A1', category: '学校' },
  { id: 301, hu: 'tanár', ja: '先生', pos: '名詞', level: 'A1', category: '学校' },
  { id: 302, hu: 'diák', ja: '学生', pos: '名詞', level: 'A1', category: '学校' },
  { id: 303, hu: 'könyvtár', ja: '図書館', pos: '名詞', level: 'A1', category: '学校' },
  { id: 304, hu: 'vizsga', ja: '試験', pos: '名詞', level: 'A2', category: '学校' },
  { id: 305, hu: 'óra', ja: '授業', pos: '名詞', level: 'A1', category: '学校' },
  { id: 306, hu: 'füzet', ja: 'ノート', pos: '名詞', level: 'A1', category: '学校' },
  { id: 307, hu: 'toll', ja: 'ペン', pos: '名詞', level: 'A1', category: '学校' },
  { id: 308, hu: 'nyelv', ja: '言語', pos: '名詞', level: 'A1', category: '学校' },
  { id: 309, hu: 'szótár', ja: '辞書', pos: '名詞', level: 'A2', category: '学校' },

  // --- 仕事・ビジネス (Work & Business) ---
  { id: 320, hu: 'munka', ja: '仕事', pos: '名詞', level: 'A1', category: '仕事' },
  { id: 321, hu: 'főnök', ja: '上司', pos: '名詞', level: 'A2', category: '仕事' },
  { id: 322, hu: 'kolléga', ja: '同僚', pos: '名詞', level: 'A2', category: '仕事' },
  { id: 323, hu: 'értekezlet', ja: '会議', pos: '名詞', level: 'B1', category: '仕事' },
  { id: 324, hu: 'siker', ja: '成功', pos: '名詞', level: 'A2', category: '仕事' },
  { id: 325, hu: 'pénz', ja: 'お金', pos: '名詞', level: 'A1', category: '仕事' },
  { id: 326, hu: 'fizetés', ja: '給料', pos: '名詞', level: 'A2', category: '仕事' },
  { id: 327, hu: 'szabadság', ja: '休暇', pos: '名詞', level: 'A2', category: '日常' },

  // --- その他便利な表現 (Useful Expressions) ---
  { id: 340, hu: 'szép napot!', ja: '良い一日を！', pos: '挨拶', level: 'A1', category: '挨拶' },
  { id: 341, hu: 'egészségedre!', ja: '乾杯！ / お大事に！', pos: '挨拶', level: 'A1', category: '文化' },
  { id: 342, hu: 'jó étvágyat!', ja: '召し上がれ！', pos: '挨拶', level: 'A1', category: '文化' },
  { id: 343, hu: 'szívesen', ja: 'どういたしまして', pos: '間投詞', level: 'A1', category: '挨拶' },
  { id: 344, hu: 'bocsánat', ja: 'ごめんなさい', pos: '間投詞', level: 'A1', category: '挨拶' },
  { id: 345, hu: 'persze', ja: 'もちろんです', pos: '副詞', level: 'A1', category: '会話' },
  { id: 346, hu: 'talán', ja: 'たぶん', pos: '副詞', level: 'A1', category: '会話' },
  { id: 347, hu: 'tényleg?', ja: '本当ですか？', pos: '副詞', level: 'A1', category: '会話' },
  { id: 348, hu: 'nem baj', ja: '大丈夫です', pos: '熟語', level: 'A1', category: '会話' },
  { id: 349, hu: 'szeretlek', ja: '愛しています', pos: '動詞句', level: 'A1', category: '感情' },
];

export const words = data.sort((a, b) => a.id - b.id);
